apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-local
spec:
  replicas: 4
  selector:
    matchLabels:
      run: guestbook-local
  template:
    metadata:
      labels:
        run: guestbook-local
    spec:
      containers:
      - name: guestbook-local
        image: detteiu/karbon-training01:v1
        ports:
        - containerPort: 3000
