apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-color
spec:
  selector:
    matchLabels:
      run: webapp-color
  replicas: 8
  template:
    metadata:
      labels:
        run: webapp-color
      annotations:
        kubernetes.io/change-cause: webapp-color apps update to version.2
    spec:
      containers:
      - name: webapp-color
        image: kodekloud/webapp-color:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: webapp-color
