kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: sample-statefuleset
spec:
  serviceName: statefuleset-service
  replicas: 3
  # これを定義することでRollingUpdateされる
  updateStrategy:
    # RollingUpdate or OnDelete。Default: RollingUpdate
    # OnDeleteだとPodは自動的に更新されず、手動でPodを削除すると、自動的に新しいPodが起動される。
    type: RollingUpdate
    ##############################################################
    # partitionを設定すると、指定した番号以上のPodのみが更新される。
    # 以下の例だと、{Pod名}-1以上のPodが更新され、{Pod名}-0は更新されない。
    ##############################################################
    #rollingUpdate:
    #  partition: 1
  # Podの定義
  template:
    metadata:
      labels:
        app: sample-statefuleset
    spec:
      containers:
      - name: sample-container
        image: gcr.io/google-samples/hello-app:1.0
        volumeMounts:
        - name: sample-pvc
          mountPath: /var/data
  # 以下のTemplateでPersistentVolumeClaimを作成する
  volumeClaimTemplates:
  - metadata:
      name: sample-pvc
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce
      # storageClassNameを省略するとHostPathでホストOS上にmountされる
      storageClassName: default-storageclass
