apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-daemonset
spec:
  selector:
    matchLabels:
      app: sample-daemonset
  template:
    metadata:
      labels:
        app: sample-daemonset
    spec:
      containers:
        - name: sample-daemonset
          image: detteiu/karbon-training01
          ports:
            - containerPort: 3000https://github.com/hanakara-milk/Karbon-basics
